In [1]:
import pandas as pd

In [2]:
article_df = pd.read_excel('../data-dir/kakao-article-preprocessed.xlsx')
community_df = pd.read_excel('../data-dir/kakao-community-preprocessed.xlsx')
stock_df = pd.read_excel('../data-dir/kakao-stock-preprocessed.xlsx')
total_df = stock_df.set_index('DayIndex')

In [3]:
total_df

                   Open      High       Low     Close
DayIndex
2022-10-13_AM  0.748025  0.748025  0.705613  0.715593
2022-10-13_PM  0.714761  0.718919  0.705613  0.645738
2022-10-14_AM  0.734719  0.772141  0.734719  0.765489
2022-10-14_PM  0.767152  0.775468  0.763825  0.773805
2022-10-17_AM  0.773805  0.773805  0.693139  0.729730
...                 ...       ...       ...       ...
2023-01-12_PM  0.946778  0.950104  0.941788  0.941788
2023-01-13_AM  0.951767  0.966736  0.941788  0.951767
2023-01-13_PM  0.951767  0.955094  0.946778  0.951767
2023-01-16_AM  0.950104  1.000000  0.950104  0.988358
2023-01-16_PM  0.990021  0.996674  0.983368  0.991684

[132 rows x 4 columns]

## Aggregation

In [4]:
community_df = community_df.drop('Unnamed: 0', axis=1)
article_df = article_df.drop('Unnamed: 0', axis=1)

In [5]:
total_df['CommunityText'] = community_df.groupby('DayIndex')['CommunityText'].apply(list)
total_df['ArticleText'] = article_df.groupby('DayIndex')['ArticleText'].apply(list)

In [6]:
total_df

,Open,High,Low,Close,CommunityText,ArticleText
DayIndex,,,,,,
2022-10-13_AM,0.748025,0.748025,0.705613,0.715593,NaN,NaN
2022-10-13_PM,0.714761,0.718919,0.705613,0.645738,NaN,NaN
2022-10-14_AM,0.734719,0.772141,0.734719,0.765489,[씨없는 카카오?알맹이가 없어 껍데기뿐인 카카오를 어디다 쓰나?강방천씨 나좀 이해좀...,NaN
2022-10-14_PM,0.767152,0.775468,0.763825,0.773805,"[다음주에 엄청 빠지겠네..., 51000~51300원 사이에서80%매도 기다린다 ...",NaN
2022-10-17_AM,0.773805,0.773805,0.693139,0.729730,[카카오관련주 모두 지난 금요일 대량거래후유증 크겠다.n추가상승 노리고 매수후 보...,NaN
...,...,...,...,...,...,...
2023-01-12_PM,0.946778,0.950104,0.941788,0.941788,NaN,NaN
2023-01-13_AM,0.951767,0.966736,0.941788,0.951767,NaN,NaN
2023-01-13_PM,0.951767,0.955094,0.946778,0.951767,NaN,NaN
2023-01-16_AM,0.950104,1.000000,0.950104,0.988358,NaN,NaN
2023-01-16_PM,0.990021,0.996674,0.983368,0.991684,NaN,NaN

In [8]:
total_df[total_df['CommunityText'].isna()].

,Open,High,Low,Close,CommunityText,ArticleText
DayIndex,,,,,,
2022-10-13_AM,0.748025,0.748025,0.705613,0.715593,NaN,NaN
2022-10-13_PM,0.714761,0.718919,0.705613,0.645738,NaN,NaN
2022-10-17_PM,0.728898,0.728898,0.719751,0.723077,NaN,NaN
2022-10-18_AM,0.723077,0.752183,0.723077,0.733888,NaN,NaN
2022-10-18_PM,0.734719,0.740541,0.732225,0.740541,NaN,NaN
2022-10-19_AM,0.740541,0.785447,0.740541,0.758836,NaN,NaN
2022-10-19_PM,0.760499,0.760499,0.744699,0.747193,NaN,NaN
2023-01-09_AM,0.870270,0.916840,0.870270,0.916840,NaN,NaN
2023-01-09_PM,0.916840,0.936798,0.913514,0.935135,NaN,NaN
2023-01-10_AM,0.935135,0.945114,0.923493,0.933472,NaN,NaN
2023-01-10_PM,0.935135,0.935135,0.923493,0.928482,NaN,NaN
2023-01-11_AM,0.928482,0.958420,0.916840,0.950104,NaN,NaN
2023-01-11_PM,0.951767,0.955094,0.948441,0.948441,NaN,NaN
2023-01-12_AM,0.948441,0.971726,0.935135,0.945114,NaN,NaN
2023-01-12_PM,0.946778,0.950104,0.941788,0.941788,NaN,NaN
2023-01-13_AM,0.951767,0.966736,0.941788,0.951767,NaN,NaN
2023-01-13_PM,0.951767,0.955094,0.946778,0.951767,NaN,NaN
2023-01-16_AM,0.950104,1.000000,0.950104,0.988358,NaN,NaN
2023-01-16_PM,0.990021,0.996674,0.983368,0.991684,NaN,NaN

In [ ]:
total_df = total_df.dropna(axis=0).reset_index()
total_df.head()

,DayIndex,Open,High,Low,Close,CommunityText,ArticleText
0,2022-12-16_PM,0.825364,0.827027,0.818711,0.822037,[아니 진짜 ㅅㅂ이럴거면 주식사지말고 공매도 치는게 돈버는거아니냐 ㅡㅡ 탈출만하면 ...,"[엔씨, 전사 재해 복구 모의 훈련 실시…지진·화재 등 대비한다= 엔씨소프트가 ‘I..."
1,2022-12-19_PM,0.841996,0.848649,0.841996,0.845322,[카카오가 2프로나 올랏네 우와 무슨일이냐 --_-ㅋㅋ4만간다고 해서 개쫄앗느데 ㅋ...,[반도체와 클라우드는 무슨 관계?지난주 과학기술정보통신부는 경기창조경제혁신센터서 ‘...
2,2022-12-20_AM,0.846985,0.846985,0.825364,0.828690,"[1월9일중국결해제 카카오간다텐센트3%상승중 카카오10만갑니다, 개장전 빠르게 체크...","[엔씨소프트, 전사 재해 복구 모의 훈련 실시엔씨소프트는 서비스 연속성 유지를 위한..."
3,2022-12-22_AM,0.833680,0.845322,0.818711,0.833680,[카카오 목표주가 변동요약[ FS리서치 ] 12/22일 목표주가 변동 기업 보고서요...,"[화재와 먹통이 휩쓴 자리, 남은 건 규제 후폭풍네이버와 카카오는 다사다난한 한 해..."
4,2022-12-22_PM,0.833680,0.837006,0.832017,0.835343,[빨리 빨리 올라가자오늘 같은 날은 인간적으로 빨리 빨리 올라가자 힘을 내서 빨리 ...,[실종된 자율규제새해 플랫폼 업계를 짓누르는 화두가 두 가지 있다. 온라인 플랫폼 ...

## Labeling

In [ ]:
mean = total_df[['Open', 'Close', 'High', 'Low']].mean(axis=1)
mean

0     0.823285
1     0.844491
2     0.837006
3     0.832848
4     0.834511
5     0.815385
6     0.817464
7     0.812474
8     0.792516
9     0.819958
10    0.840748
11    0.862370
12    0.879002
13    0.874428
14    0.870270
dtype: float64

In [ ]:
index = total_df['Close'] < mean
total_df['Label'] = 0
total_df.loc[index, 'Label'] = 1

df

NameError: name 'df' is not defined

In [ ]:
total_df.to_pickle('../data-dir/data-df.pkl')