In [1]:
import pandas as pd

In [2]:
community_df = pd.read_excel('../data-dir/kakao-community-preprocessed.xlsx')
stock_df = pd.read_excel('../data-dir/kakao-stock-preprocessed.xlsx')
total_df = stock_df.set_index('DayIndex')

In [3]:
total_df

                   Open      High       Low     Close
DayIndex
2022-10-13_AM  0.748025  0.748025  0.705613  0.715593
2022-10-13_PM  0.714761  0.718919  0.705613  0.645738
2022-10-14_AM  0.734719  0.772141  0.734719  0.765489
2022-10-14_PM  0.767152  0.775468  0.763825  0.773805
2022-10-17_AM  0.773805  0.773805  0.693139  0.729730
...                 ...       ...       ...       ...
2023-01-12_PM  0.946778  0.950104  0.941788  0.941788
2023-01-13_AM  0.951767  0.966736  0.941788  0.951767
2023-01-13_PM  0.951767  0.955094  0.946778  0.951767
2023-01-16_AM  0.950104  1.000000  0.950104  0.988358
2023-01-16_PM  0.990021  0.996674  0.983368  0.991684

[132 rows x 4 columns]

## Aggregation

In [4]:
community_df = community_df.drop('Unnamed: 0', axis=1)

In [5]:
total_df['CommunityText'] = community_df.groupby('DayIndex')['CommunityText'].apply(list)

In [6]:
total_df

,Open,High,Low,Close,CommunityText
DayIndex,,,,,
2022-10-13_AM,0.748025,0.748025,0.705613,0.715593,NaN
2022-10-13_PM,0.714761,0.718919,0.705613,0.645738,NaN
2022-10-14_AM,0.734719,0.772141,0.734719,0.765489,NaN
2022-10-14_PM,0.767152,0.775468,0.763825,0.773805,NaN
2022-10-17_AM,0.773805,0.773805,0.693139,0.729730,NaN
...,...,...,...,...,...
2023-01-12_PM,0.946778,0.950104,0.941788,0.941788,"[신한금투,,사랑해요 ~, 63400., 카카오엔터.. 우회상장우회상장 목적이라..."
2023-01-13_AM,0.951767,0.966736,0.941788,0.951767,"[다들힘드시죠근데요즘 무빙스탁이라고대출이자가싼곳이있던데요 어떤곳인가요대환대출, 빈살..."
2023-01-13_PM,0.951767,0.955094,0.946778,0.951767,"[63500., 푸틴과 공매는 아베곁으로좀 보내자, 개 스러기주 까까오최고가 17만..."
2023-01-16_AM,0.950104,1.000000,0.950104,0.988358,"[2030년까지 박스권이다.내말 잘들 기억해라.., 고진감래., 빨리 10만 넘어가..."
2023-01-16_PM,0.990021,0.996674,0.983368,0.991684,"[오후에 오늘은 아마도 상 뜰듯오후에 오늘은 아마도 상 뜰듯, 좋아요, 싫어요 눌러..."

In [7]:
total_df[total_df['CommunityText'].isna()].count()

Open             120
High             120
Low              120
Close            120
CommunityText      0
dtype: int64

In [8]:
total_df = total_df.dropna(axis=0).reset_index()
total_df.head()

,DayIndex,Open,High,Low,Close,CommunityText
0,2023-01-09_AM,0.870270,0.916840,0.870270,0.916840,"[아침,,뉴스에 나오더라~ 보상안까지 장사속 이라고 완전 쓰레기 기업 이라는 거지!..."
1,2023-01-09_PM,0.916840,0.936798,0.913514,0.935135,"[다들 매도가 저게뭔지요돈도벌수있는타이밍있지n싸게도매도한다.nㅠ ㅠ, 그분 생..."
2,2023-01-10_AM,0.935135,0.945114,0.923493,0.933472,[이제는 자유민주주의가아닌 인민민주주의시대온건가 ???????????????????...
3,2023-01-10_PM,0.935135,0.935135,0.923493,0.928482,"[이제 시작이다아직 바닥이다.이제 시작이다, 잘 먹고 갑니다더 갈거 같지만 일단 현..."
4,2023-01-11_AM,0.928482,0.958420,0.916840,0.950104,"[오늘은 진짜냐위로가냐 아래로 기는가, 7만원 가즈아할 수 있어!!!!, 시초에 띄..."

## Labeling

In [20]:
mean = total_df[['Open', 'Close', 'High', 'Low']].mean(axis=1)
mean = mean.shift(1)
mean.loc[0] = 0
mean

0     0.000000
1     0.893555
2     0.925572
3     0.934304
4     0.930561
5     0.938462
6     0.950936
7     0.950104
8     0.945114
9     0.953015
10    0.951351
11    0.972141
dtype: float64

In [21]:
index = total_df['Close'] < mean
total_df['Label'] = 0
total_df.loc[index, 'Label'] = 1

total_df

,DayIndex,Open,High,Low,Close,CommunityText,Label
0,2023-01-09_AM,0.870270,0.916840,0.870270,0.916840,"[아침,,뉴스에 나오더라~ 보상안까지 장사속 이라고 완전 쓰레기 기업 이라는 거지!...",0
1,2023-01-09_PM,0.916840,0.936798,0.913514,0.935135,"[다들 매도가 저게뭔지요돈도벌수있는타이밍있지n싸게도매도한다.nㅠ ㅠ, 그분 생...",0
2,2023-01-10_AM,0.935135,0.945114,0.923493,0.933472,[이제는 자유민주주의가아닌 인민민주주의시대온건가 ???????????????????...,0
3,2023-01-10_PM,0.935135,0.935135,0.923493,0.928482,"[이제 시작이다아직 바닥이다.이제 시작이다, 잘 먹고 갑니다더 갈거 같지만 일단 현...",1
4,2023-01-11_AM,0.928482,0.958420,0.916840,0.950104,"[오늘은 진짜냐위로가냐 아래로 기는가, 7만원 가즈아할 수 있어!!!!, 시초에 띄...",0
5,2023-01-11_PM,0.951767,0.955094,0.948441,0.948441,"[*속보*코콤 코맥스보다 실적좋고 세계가 인정한 ""아이디스"" 가 있다! 기대하라강남...",0
6,2023-01-12_AM,0.948441,0.971726,0.935135,0.945114,"[나스닥 2%반등 카카오 네이버 삼성전자 폭등99.000, 나스닥 2%반등 카카오 ...",1
7,2023-01-12_PM,0.946778,0.950104,0.941788,0.941788,"[신한금투,,사랑해요 ~, 63400., 카카오엔터.. 우회상장우회상장 목적이라...",1
8,2023-01-13_AM,0.951767,0.966736,0.941788,0.951767,"[다들힘드시죠근데요즘 무빙스탁이라고대출이자가싼곳이있던데요 어떤곳인가요대환대출, 빈살...",0
9,2023-01-13_PM,0.951767,0.955094,0.946778,0.951767,"[63500., 푸틴과 공매는 아베곁으로좀 보내자, 개 스러기주 까까오최고가 17만...",1
10,2023-01-16_AM,0.950104,1.000000,0.950104,0.988358,"[2030년까지 박스권이다.내말 잘들 기억해라.., 고진감래., 빨리 10만 넘어가...",0
11,2023-01-16_PM,0.990021,0.996674,0.983368,0.991684,"[오후에 오늘은 아마도 상 뜰듯오후에 오늘은 아마도 상 뜰듯, 좋아요, 싫어요 눌러...",0

In [11]:
total_df.to_pickle('../data-dir/data-df.pkl')